---
title: "Radiation"
author: "Michael Bennett"
date: "2/26/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(tidyverse)
lter <- read.csv("D:/Data/Earth/lab4_data.csv")
lter$Date <- mdy(lter$Date)
```

```{r Net}
lter %>%
  drop_na(Net.Radiation..W.m2.) %>%
  ggplot(aes(x = Date, y = Net.Radiation..W.m2., colour = after_stat(y < 0))) +
  geom_line() +
  geom_hline(yintercept = 0, linetype = 'dashed', col = 'black') +
  scale_colour_manual(values = c("red3", "blue")) +
  scale_x_date(date_breaks = '1 month', date_labels = '%B') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), 
        legend.position = c(0.90, 0.15), 
        panel.grid.minor = element_blank()) +
  labs(title = "Niwot Ridge LTER Site", subtitle = "Net Radiation", 
       x = "Date (2000)", 
       y = "Radiation (W/m2)", 
       caption = "Radiation data from the Subnivean Laboratory")
```

```{r Incident & reflected}
lter %>%
  drop_na(Incident.SW..W.m2., Reflected.SW..W.m2.) %>%
  ggplot(aes(x = Date, y = Incident.SW..W.m2.)) + 
  geom_line(aes(y = Incident.SW..W.m2., colour = "Incident")) + 
  geom_line(aes(y = Reflected.SW..W.m2., colour = "Reflected")) +
  scale_color_manual(values = c("blue", "red3")) +
  scale_x_date(date_breaks = '1 month', date_labels = '%B') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), 
        legend.position = c(0.15, 0.85), legend.title = element_blank(), 
        panel.grid.minor = element_blank()) +
  labs(title = "Niwot Ridge LTER Site", 
       subtitle = "Incident & Reflected Solar Radiation", 
       x = "Date (2000)", 
       y = "Radiation (W/m2)", fill = "Reflected",
       caption = "Radiation data from the Subnivean Laboratory")
```

```{r LW}
lter %>%
  drop_na(Terrest.LW..W.m2., Atmospheric.LW..W.m2.) %>%
  ggplot(aes(x = Date, y = Terrest.LW..W.m2.)) + 
  geom_line(aes(y = Atmospheric.LW..W.m2., colour = "Atmospheric")) +
  geom_line(aes(y = Terrest.LW..W.m2., colour = "Terrestrial")) + 
  scale_color_manual(values = c("blue", "red3")) +
  guides(colour = guide_legend(reverse = T)) +
  scale_x_date(date_breaks = '1 month', date_labels = '%B') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), 
        legend.position = c(0.85, 0.15), legend.title = element_blank(),
        panel.grid.minor = element_blank()) +
  labs(title = "Niwot Ridge LTER Site", 
       subtitle = "Terrestrial & Atmospheric Longwave Radiation", 
       x = "Date (2000)", 
       y = "Radiation (W/m2)", fill = "Atmospheric",
       caption = "Radiation data from the Subnivean Laboratory")
```

